### ISSUE TITLE
kubernetes  on azure is broken with docker version 1.13.0

### ISSUE THREAD

**Issue by rathir** [colemickens/azure-kubernetes-status#20]
I see that Kubernetes v1.5.1 is deployed on azure nodes and I am hitting the below bug.

https://github.com/kubernetes/kubeadm/issues/102

Kube version:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by colemickens** [comment]
Can you supply more information? That linked issue is about `kubeadm` + cni plugins, neither of which we use right now.

The output showing the event for the Pod, and the logs from `kube-controller-manager` would be helpful. (`kubectl logs --namespace kube-system kube-controller-manager...`)

**Comment by rathir** [comment]
This is what I found out.  Kube Dashboard was not able to talk to API server and kept restarting .  I confirmed that service account and token all looked good. Basically API server endpoint 10.0.0.1 was not reachable.
Then I noticed below logs in kubectl proxy:
```
I0119 01:56:41.869485       1 server.go:215] Using iptables Proxier.
W0119 01:56:41.872753       1 proxier.go:254] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0119 01:56:41.872829       1 server.go:227] Tearing down userspace rules.
I0119 01:56:41.889199       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0119 01:56:41.889771       1 conntrack.go:66] Setting conntrack hashsize to 32768
I0119 01:56:41.890028       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0119 01:56:41.890059       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
```

Once I applied the workaround mentioned in the referred bug,   dashboard pod could talk to API service and I can see logs in kube-proxy about "opened iptables".
```
kubectl -n kube-system get ds -l "component=kube-proxy" -o json | jq ".items[0].spec.template.spec.containers[0].command |= .+ [\"--proxy-mode=userspace\"]" | kubectl apply -f - && kubectl -n kube-system delete pods -l "component=kube-proxy"
```

I can't provide any more logs since I took  setup down.

**Comment by rathir** [comment]
Actually I am not sure if it is related to newer version.  I managed to downgrade setup to 1.4.6 version and still see the same issue.  I have attached kube-controller-manager logs
[kube-controller-manager.txt](https://github.com/colemickens/azure-kubernetes-status/files/715963/kube-controller-manager.txt)
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", 
GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
kube-proxy logs
```
I0119 07:10:39.408594       1 server.go:203] Using iptables Proxier.
I0119 07:10:39.410185       1 server.go:215] Tearing down userspace rules.
I0119 07:10:39.420716       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0119 07:10:39.421098       1 conntrack.go:66] Setting conntrack hashsize to 32768
I0119 07:10:39.421540       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0119 07:10:39.421570       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
```

**Comment by colemickens** [comment]
That is helpful. Can you answer these questions for me:

1. When did you deploy this cluster?

2. Did you run system updates? If so, did you reboot?

Have you deployed clusters previously and/or do you have any others operational right now?

**Comment by colemickens** [comment]
(Also, when you say you downgraded, did you actually downgrade kubelets as well?)

**Comment by rathir** [comment]
1.  This was deployed in last 1hr.
2.  This is totally new cluster. I modified deployment template and parameters to change version to 1.4.6 
3.  I have deployed previously. But don't have any other operational now.

**Comment by rathir** [comment]
So before I apply the workaround mentioned above,  there is only DNAT rule for 10.0.0.1 like this
```
Chain KUBE-SEP-TKA5O4UKOR545GXM (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.240.255.5         0.0.0.0/0            /* default/kubernetes:https */
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: SET name: KUBE-SEP-TKA5O4UKOR545GXM side: source mask: 255.255.255.255 tcp to:10.240.255.5:443

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination         
KUBE-SVC-NPX46M4PTMTKRN6Y  tcp  --  0.0.0.0/0            10.0.0.1             /* default/kubernetes:https cluster IP */ tcp dpt:443
```
After applying the workaround, they totally change
```
Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            10.0.0.1             /* default/kubernetes:https */ tcp dpt:443 redir ports 40624
Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            10.0.0.1             /* default/kubernetes:https */ tcp dpt:443 to:10.240.0.5:40624
```

**Comment by colemickens** [comment]
You'd need to post the full output to compare, those look like different sections of a larger output.

**Comment by rathir** [comment]
Attached file contains output before and after workaround.
[iptables.txt](https://github.com/colemickens/azure-kubernetes-status/files/716300/iptables.txt)

**Comment by colemickens** [comment]
I'm not an iptables expert, but I'd expect things to look fairly different since the workaround is moving logic out of iptables into userspace. 

Plus, why would it be a problem of kube-proxy, since 1.4.6+iptables mode kube-proxy was working just a few days ago.

A different workaround for this issue is downgrading docker from `1.13.0` to `1.12.6`.

**Comment by rathir** [comment]
Yeah, I would like to try that. Is there a way to specify docker version before deploying new cluster ?

**Comment by rathir** [comment]
Okay,  I managed to downgrade to 1.12.6 on my setup and everything is working perfectly.  iptable rules are same as I put earlier when I applied the workaround.  So clearly issue is with docker version 1.13.0 on Azure kubernetes cluster.

**Comment by colemickens** [comment]
So you downgraded to 1.12.6. Did you also undo the `kube-proxy` workaround? You're sure kube-proxy is in iptables mode? If so, can you attach the iptables dump again?

**Comment by rathir** [comment]
You are right.  I didn't undo kube-proxy workaround.  So now I changed back *iptables* mode and yes iptable rules look different between these two modes.  But it is working for me now even  with *iptables* mode.  Working iptables dump is attached.
[working-iptables.txt](https://github.com/colemickens/azure-kubernetes-status/files/717674/working-iptables.txt)

**Comment by colemickens** [comment]
Okay. I'm still assuming this is just related to the docker version.

**Comment by colemickens** [comment]
Please see this issue for details about an ongoing issue with the Azure Container Service: [Azure/ACS #3 - Kubernetes Clusters Broken after Deployment or Unattended Upgrades](https://github.com/Azure/ACS/issues/3).

Additionally, we plan to use that repo (https://github.com/Azure/ACS) to handle these sorts of events in the future. Please consider subscribing so that you are notified in the future.

For now, I am going to close this out. If there are follow up questions, please put them on that issue so everyone can benefit from the answer in a single place. (**Especially since this repo is deprecated! I'll be turning off Issues soon...**)

Thanks.
