### ISSUE TITLE
Azure subnet reserved IPs

### ISSUE THREAD

**Issue by edevil** [colemickens/azure-kubernetes-status#8]
Does the Azure cloud provider correctly assign the pod-cidrs taking into account that Azure reserves some IPs on each subnet? I ask this because I think I ran into this issue while manually creating subnets before Kube 1.4.

Azure documentation:

> Are there any restrictions on using IP addresses within these subnets?
> Azure reserves some IP addresses within each subnet. The first and last IP addresses of the subnets are reserved for protocol conformance, along with 3 more addresses used for Azure services.

I created subnet 10.2.10.0/24 for a node's podCIDR and specified --pod-cidr=10.2.10.0/24 but this pod in particular could not be routed:

```
Name:       ...
Namespace:  ...
Node:       10.0.3.10/10.0.3.10
Start Time: Fri, 09 Sep 2016 10:02:02 +0100
Labels:     ...
Status:     Running
IP:     10.2.10.4
```

10.2.10.4 is still a reserved IP, right?

**Comment by edevil** [comment]
Hum, I just noticed I have a pod with IP 10.2.10.3 and it's working fine, so disregard this issue please.

**Comment by colemickens** [comment]
(The detail here is that we don't provision subnets for each VM. We just setup the "User Defined Routes" to route the cidrs to the appropriate node. This avoids the caveat of reserved subnet IPs.)
